export const optionsCs = [
  { label: 'Inferno', value: 'Inferno' },
  { label: 'Lake', value: 'Lake' },
  { label: 'Rialto', value: 'Rialto' },
  { label: 'Shortdust', value: 'Shortdust' },
  { label: 'Italy', value: 'Italy' },
  { label: 'Miami', value: 'Miami' },
  { label: 'Militia', value: 'Militia' },
  { label: 'Office', value: 'Office' },
  { label: 'Cache', value: 'Cache' },
  { label: 'Canals', value: 'Canals' },
  { label: 'Dust', value: 'Dust' },
  { label: 'Dust II', value: 'Dust II' },
  { label: 'Fastline', value: 'Fastline' },
  { label: 'Mirage', value: 'Mirage' },
  { label: 'Nuke', value: 'Nuke' },
  { label: 'Overpass', value: 'Overpass' },
  { label: 'Piranesi', value: 'Piranesi' },
  { label: 'Storm', value: 'Storm' },
];
export const optionsDota = [
  { label: 'Официальная карта', value: 'Официальная карта' },
  { label: 'Dota Auto Chess', value: 'Dota Auto Chess' },
  { label: 'Atomic War', value: 'Atomic War' },
  { label: 'Custom Hero Chaos', value: 'Custom Hero Chaos' },
  { label: 'Custom Hero Clash', value: 'Custom Hero Clash' },
  { label: 'Хранитель Самсары', value: 'Хранитель Самсары' },
  { label: 'Dawn of War', value: 'Dawn of War' },
  { label: 'Random Defense Adventure', value: 'Random Defense Adventure' },
  { label: 'Overthrow', value: 'Overthrow' },
];
export const optionsTf = [
  { label: '2Fort', value: '2Fort' },
  { label: '2Fort Invasion', value: '2Fort Invasion' },
  { label: 'Double Cross', value: 'Double Cross' },
  { label: 'Doublefrost', value: 'Custom Hero Chaos' },
  { label: 'Landfall', value: 'Landfall' },
  { label: 'Sawmill', value: 'Sawmill' },
  { label: 'Snowfall', value: 'Snowfall' },
  { label: 'Well', value: 'Well' },
  { label: 'Badlands', value: 'Badlands' },
  { label: 'Coldfront', value: 'Coldfront' },
  { label: 'Fastlane', value: 'Fastlane' },
  { label: 'Foundry', value: 'Foundry' },
  { label: 'Freight', value: 'Freight' },
  { label: 'Granary', value: 'Granary' },
  { label: 'Metalworks', value: 'Metalworks' },
  { label: 'Powerhouse', value: 'Powerhouse' },
  { label: 'Process', value: 'Process' },
];
export const optionsLol = [
  { label: 'Официальная карта', value: 'Официальная карта', style: { color: 'red' } },
];
export const GameOption = {
  CS: optionsCs,
  DOTA: optionsDota,
  TF: optionsTf,
  LOL: optionsLol,
};
